---
title: "viz_part_01"
author: "Yujie Huang"
output: github_document
date: "2022-09-29"
editor_options: 
  chunk_output_type: console
---

## let's import data

```{r}
library(tidyverse)

```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
   month = lubridate::floor_date(date, unit = "month")) %>%  
  select(name, id, everything())
```

## group_by

```{r}
weather_df %>%
  group_by(name, month)
```

## summarzie 

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n())
```

## count

```{r}
weather_df %>%
  count(month, name = "n_obs")
```

## Don't do table! don't use `table()` function
```{r}
weather_df %>%
  pull(month) %>% 
  table
```

## multiple summaries
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))

#"n_distinct" add some only one column/variable to get that variable's total number
```

## 2x2 table
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(count = n())



weather_df %>% 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

##General summary
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    mean_tmax = mean(tmax),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(across(tmin:prcp, mean))
```

## summarize and plot
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax)
```

```{r}
#use `knitr::kable()` to get a table format instead of a data frame format

weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digits=2)
```

## Grouped mutates
```{r}
#use `mutate` and `mean` to add a new mean column

weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

## lagged observations 
```{r}
#Beside the lag fuction, there is also a lead function from the other direction.

weather_df %>%
  group_by(name) %>%
  mutate(yesterday_tmax = lag(tmax))

weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax))
```

## One other window function
```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(
    tmax_rank= min_rank(tmax)
  ) %>% 
  filter(tmax_rank < 4) %>%
  arrange(name, month, tmax_rank)
  
```

