---
title: "viz_part_01"
author: "Yujie Huang"
output: htlm_document
date: "2022-09-29"
editor_options: 
  chunk_output_type: console
---

# let's import data

```{r}
library(tidyverse)
library(ggridges)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
##let's make a scatterplot

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax)) + geom_point()
```
```{r}
weather_df %>%
  drop_na() %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_scatterplot = 
  weather_df %>% 
  drop_na () %>% 
  ggplot (aes(x=tmin, y=tmax))

weather_scatterplot+geom_point()

  
```

```{r}
 weather_df %>% 
  drop_na () %>% 
  ggplot (aes(x=tmin, y=tmax, color=name))+geom_point()

```
### if add "color=name" in the "ggplot" we can apply it all ggplots. if add "color=name" in the "geom_point" we can apply it in that geom point figure.


```{r}
 weather_df %>% 
  drop_na () %>% 
  ggplot (aes(x=tmin, y=tmax))+geom_point(aes(color=name))+
geom_smooth()
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size=prcp),alpha=0.3)+
  geom_smooth(se = FALSE) +
  facet_grid(.~name)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

## some quick studd

```{r}
weather_df %>% 
  ggplot (aes(x=tmin, y=tmax))+ geom_hex()

```
## univariate plots

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```

```{r}
weather_df %>% 
  ggplot (aes(x=name, y=tmax, fill=name))+
  geom_boxplot()
```

```{r}
weather_df %>% 
  ggplot (aes(x=name, y=tmax, fill=name))+
  geom_violin()
```
##saving and embedding plots

```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```













